from django.db import models

# Create your models here.
def convertir_a_decimal(x):
    num = int(x, 16)
    return num

class enodeb(models.Model): #1
    enb_id = models.CharField(max_length=50) #0x19B 20-bit eNB identifier.
    name = models.CharField(max_length=100)
    mcc = models.CharField(max_length=50)  #Mobile Country Code
    mnc = models.CharField(max_length=50)  # 01 Mobile Network Code
    mme_addr = models.CharField(max_length=50)  #127.0.1.100 IP address of MME for S1 connnection
    gtp_bind_addr = models.CharField(max_length=50)  # 127.0.1.1 Local IP address to bind for GTP connection
    gtp_advertise_addr = models.CharField(max_length=50) # IP address of eNB to advertise for DL GTP-U Traffic
    s1c_bind_addr = models.CharField(max_length=50)  # 127.0.1.1 Local IP address to bind for S1AP connection
    s1c_bind_port = models.CharField(max_length=50)  #Source port for S1AP connection (0 means any)
    n_prb = models.CharField(max_length=50)  #Number of Physical Resource Blocks (6,15,25,50,75,100)
    tm = models.CharField(max_length=50)  #Transmission mode 1-4 (TM1 default)
    nof_ports = models.CharField(max_length=50)  #Number of Tx ports (1 port default, set to 2 for TM2/3/4)
    p_a = models.CharField(max_length=50)

    def get_enb_id(self):
        x = convertir_a_decimal(self.enb_id)
        return x

class enb_files(models.Model): #2
    sib_config = models.CharField(max_length=50) # 'sib.conf' SIB1, SIB2 and SIB3 configuration file
    rr_config  = models.CharField(max_length=50) # 'rr.conf' Radio Resources configuration file 
    rb_config = models.CharField(max_length=50) # 'rb.conf' SRB/DRB configuration file 

class rf(models.Model): #3
    dl_earfcn = models.CharField(max_length=50)
    srate = models.CharField(max_length=50)
    tx_gain = models.CharField(max_length=50) 
    rx_gain = models.CharField(max_length=50)
    tx_gain0 = models.CharField(max_length=50)
    tx_gain1 = models.CharField(max_length=50)
    tx_gain2 = models.CharField(max_length=50)
    tx_gain3 = models.CharField(max_length=50)
    tx_gain4 = models.CharField(max_length=50)
    dl_freq = models.CharField(max_length=50) 
    ul_freq = models.CharField(max_length=50) 
    device_name = models.CharField(max_length=50) 
    device_args = models.CharField(max_length=50) 
    time_adv_nsamples= models.CharField(max_length=50) 

class gui(models.Model):#4
    enable = models.BooleanField()

class pcap(models.Model):#5
    enable = models.BooleanField() 
    filename = models.CharField(max_length=50) 
    nr_filename = models.CharField(max_length=50) 
    s1ap_enable = models.BooleanField() 
    s1ap_filename = models.CharField(max_length=50)
    ngap_enable = models.BooleanField()
    ngap_filename = models.CharField(max_length=50)
    mac_net_enable = models.CharField(max_length=50) 
    bind_ip = models.CharField(max_length=50) 
    bind_port = models.CharField(max_length=50) 
    client_ip = models.CharField(max_length=50) 
    client_port = models.CharField(max_length=50) 

class log(models.Model):
    rf_level = models.CharField(max_length=50)
    phy_level = models.CharField(max_length=50)
    phy_hex_limit = models.CharField(max_length=50)
    phy_lib_level = models.CharField(max_length=50)
    mac_level = models.CharField(max_length=50)
    mac_hex_limit = models.CharField(max_length=50)
    rlc_level = models.CharField(max_length=50)
    rlc_hex_limit = models.CharField(max_length=50)
    pdcp_level = models.CharField(max_length=50)
    pdcp_hex_limit = models.CharField(max_length=50)
    rrc_level = models.CharField(max_length=50)
    rrc_hex_limit = models.CharField(max_length=50)
    gtpu_level = models.CharField(max_length=50)
    gtpu_hex_limit = models.CharField(max_length=50)
    s1ap_level = models.CharField(max_length=50)
    s1ap_hex_limit = models.CharField(max_length=50)
    stack_level = models.CharField(max_length=50)
    stack_hex_limit = models.CharField(max_length=50)
    all_level = models.CharField(max_length=50)
    all_hex_limit = models.CharField(max_length=50)
    filename = models.CharField(max_length=50)
    file_max_size = models.IntegerField()

class scheduler(models.Model):
    policy = models.CharField(max_length=50) 
    policy_args = models.CharField(max_length=50)
    min_aggr_level = models.CharField(max_length=50)
    max_aggr_level = models.CharField(max_length=50)
    adaptive_aggr_level = models.BooleanField()
    pdsch_mcs = models.CharField(max_length=50)
    pdsch_max_mcs = models.CharField(max_length=50)
    pusch_mcs = models.CharField(max_length=50)
    pusch_max_mcs = models.CharField(max_length=50)
    min_nof_ctrl_symbols = models.CharField(max_length=50)
    max_nof_ctrl_symbols = models.CharField(max_length=50)
    pucch_multiplex_enable = models.BooleanField()
    pucch_harq_max_rb = models.CharField(max_length=50)
    target_bler = models.CharField(max_length=50)
    max_delta_dl_cqi = models.CharField(max_length=50)
    max_delta_ul_snr = models.CharField(max_length=50)
    adaptive_dl_mcs_step_size = models.CharField(max_length=50)
    adaptive_ul_mcs_step_size = models.CharField(max_length=50)
    min_tpc_tti_interval = models.CharField(max_length=50)
    ul_snr_avg_alpha=models.CharField(max_length=50)
    init_ul_snr_value=models.CharField(max_length=50)
    init_dl_cqi=models.CharField(max_length=50)
    max_sib_coderate=models.CharField(max_length=50)
    pdcch_cqi_offset=models.CharField(max_length=50)
    nr_pdsch_mcs=models.CharField(max_length=50)
    nr_pusch_mcs=models.CharField(max_length=50)

class slicin(models.Model):#7
    enable_eMBB = models.BooleanField()
    enable_URLLC = models.BooleanField()
    enable_MIoT = models.BooleanField()
    eMBB_sd = models.CharField(max_length=50)
    URLLC_sd = models.CharField(max_length=50)
    MIoT_sd = models.CharField(max_length=50)
                         
class embms(models.Model):#9
    enable = models.BooleanField()
    m1u_multiaddr = models.CharField(max_length=50)
    m1u_if_addr = models.CharField(max_length=50)
    mcs = models.CharField(max_length=50)

class channel_dl(models.Model):#9
    dl_enable = models.BooleanField()
    dl_awgn_enable = models.BooleanField()
    dl_awgn_snr = models.CharField(max_length=50)
    dl_fading_enable = models.BooleanField()
    dl_fading_model = models.CharField(max_length=50)
    dl_delay_enable = models.BooleanField()
    dl_delay_period_s = models.CharField(max_length=50)
    dl_delay_init_time_s = models.CharField(max_length=50)
    dl_delay_maximum_us = models.CharField(max_length=50)
    dl_delay_minimum_us = models.CharField(max_length=50)
    dl_rlf_enable = models.BooleanField()
    dl_rlf_t_on_ms = models.CharField(max_length=50)
    dl_rlf_t_off_ms = models.CharField(max_length=50)
    dl_hst_enable = models.BooleanField()
    dl_hst_period_s = models.CharField(max_length=50)
    dl_hst_fd_hz = models.CharField(max_length=50)
    dl_hst_init_time_s = models.CharField(max_length=50)

class channel_ul(models.Model):
    ul_enable = models.BooleanField()
    ul_awgn_enable = models.BooleanField()
    ul_awgn_signal_power = models.CharField(max_length=50)
    ul_awgn_snr = models.CharField(max_length=50)
    ul_fading_enable = models.BooleanField()
    ul_fading_model = models.CharField(max_length=50)
    ul_delay_enable = models.BooleanField()
    ul_delay_period_s = models.CharField(max_length=50)
    ul_delay_init_time_s = models.CharField(max_length=50)
    ul_delay_maximum_us = models.CharField(max_length=50)
    ul_delay_minimum_us = models.CharField(max_length=50)
    ul_rlf_enable = models.BooleanField()
    ul_rlf_t_on_ms = models.CharField(max_length=50)
    ul_rlf_t_off_ms = models.CharField(max_length=50)
    ul_hst_enable = models.BooleanField()
    ul_hst_period_s = models.CharField(max_length=50)
    ul_hst_fd_hz = models.CharField(max_length=50)
    ul_hst_init_time_s = models.CharField(max_length=50)

class cfr(models.Model):#10
    enable = models.BooleanField()
    mode = models.CharField(max_length=50)
    manual_thres = models.CharField(max_length=50)
    strength = models.CharField(max_length=50)
    auto_target_papr = models.CharField(max_length=50)
    ema_alpha = models.CharField(max_length=50)

class e2_agent(models.Model):#11
    enable = models.BooleanField()
    ric_ip =  models.CharField(max_length=50)
    ric_port = models.CharField(max_length=50)
    ric_bind_ip =  models.CharField(max_length=50)
    ric_bind_port = models.CharField(max_length=50)
    max_ric_setup_retries = models.CharField(max_length=50)
    ric_connect_timer = models.CharField(max_length=50)

class expert(models.Model):#12
    pusch_max_its = models.CharField(max_length=50)
    nr_pusch_max_its = models.CharField(max_length=50)
    pusch_8bit_decoder = models.BooleanField()
    pusch_meas_evm = models.CharField(max_length=50)
    nof_prach_threads = models.CharField(max_length=50)
    equalizer_mode = models.CharField(max_length=50)
    estimator_fil_w = models.CharField(max_length=50)
    lte_sample_rates = models.CharField(max_length=50)
    print_buffer_state = models.CharField(max_length=50)
    nof_phy_threads = models.CharField(max_length=50)
    metrics_period_secs  = models.CharField(max_length=50)
    metrics_csv_enable = models.BooleanField()
    metrics_csv_filename = models.CharField(max_length=50)
    report_json_enable = models.BooleanField()
    report_json_filename = models.CharField(max_length=50)
    report_json_asn1_oct = models.BooleanField()
    alarms_log_enable = models.BooleanField()
    alarms_filename = models.CharField(max_length=50)
    tracing_enable = models.BooleanField()
    tracing_filename = models.CharField(max_length=50)
    tracing_buffcapacity = models.CharField(max_length=50)
    stdout_ts_enable = models.BooleanField()
    tx_amplitude = models.CharField(max_length=50)
    rrc_inactivity_timer = models.CharField(max_length=50)
    max_mac_dl_kos = models.CharField(max_length=50)
    max_mac_ul_kos = models.CharField(max_length=50)
    max_prach_offset_us  = models.CharField(max_length=50)
    nof_prealloc_ues = models.CharField(max_length=50)
    rlf_release_timer_ms = models.CharField(max_length=50)
    lcid_padding = models.CharField(max_length=50)
    eea_pref_list = models.CharField(max_length=50)
    eia_pref_list = models.CharField(max_length=50)
    gtpu_tunnel_timeout = models.CharField(max_length=50)
    extended_cp = models.BooleanField()
    ts1_reloc_prep_timeout = models.CharField(max_length=50)
    ts1_reloc_overall_timeout = models.CharField(max_length=50)
    rlf_release_timer_ms = models.CharField(max_length=50)
    rlf_min_ul_snr_estim = models.CharField(max_length=50)
    max_s1_setup_retries = models.CharField(max_length=50)
    s1_setup_max_retries = models.CharField(max_length=50)
    s1_connect_timer = models.CharField(max_length=50)
    rx_gain_offset = models.CharField(max_length=50)
    mac_prach_bi = models.CharField(max_length=50)
    use_cedron_f_est_alg = models.BooleanField()
    sctp_reuse_addr = models.CharField(max_length=50)
    sctp_rto_max = models.CharField(max_length=50)
    sctp_init_max_attempts = models.CharField(max_length=50)
    sctp_max_init_timeo = models.CharField(max_length=50)